shameless janitor buffs
sojourn-13/sojourn-station pull request #1420
Opened 2021-06-08 00:46 UTC by lolman360

putting this up as a draft for feedback

## About The Pull Request

adds a few upgraded janitor tools like /tg/ and etc have

advanced mop- craftable by the guild, takes a medium cell and is faster at mopping/sweeping + also generates its own slip-free mix with cell charge (not sure why you'd use this when the church now has the same thing but it doesn't need a cell and is 10x faster than the regular mop AND it also creates biomass)

big trashbag - craftable by anyone, it's just a 25% larger trashbag
industrial chemical sprayer - printable from the janitor design disk, 150 capacity 5 range version of the chemical sprayer that's obtainable without soteria help

todo: janitor design disk - can make mops, industrial sprayers, trashbags, lightbulbs, buckets and spray bottles

	

## Changelog
:cl:
add: shameless janitor buffs in the form of upgraded gear
/:cl:

2021-06-08 03:33 UTC, Trilbyspaceclone commented on code/modules/reagents/reagent_containers/spray.dm
> +	volume = 150
```suggestion
	volume = 250
```

2021-06-08 03:34 UTC, Trilbyspaceclone commented on code/game/objects/items/weapons/mop.dm
> +	sweep_time = 4
```suggestion
	sweep_time = 2
```

2021-06-11 21:36 UTC, Trilbyspaceclone requested changes
Your still deleting icons and sprites for other things

2021-06-12 15:44 UTC, Trilbyspaceclone commented
Your deleting even more icons

2021-06-21 18:59 UTC, Trilbyspaceclone approved these changes
Other then missing icons that can be fixed at a later date the pr seems good

2021-06-22 22:55 UTC, lolman360 commented
sprites fixed

2021-06-23 03:56 UTC, Trilbyspaceclone approved these changes

2021-06-25 17:44 UTC, merged