New mobs to hassel everyone
sojourn-13/sojourn-station pull request #1647
Opened 2021-07-22 06:51 UTC by Trilbyspaceclone

Fixes a bad pipe in atmos
Fixes bad pixel in deathclaws
Fixes bad paths in snake death
Adds a new nightmare type. Much deadly much rarer
Adds a new faction of monsters to beware of in the jungel, river forest and swamps
New faction is ape like birds that use simple rocks and spears at grate speeds to death with foes and when that fails use their brutal claws to nash and claw away the flesh.

2021-07-22 11:16 UTC, ThePainkiller requested changes
Some minor typo fixing

2021-07-22 11:16 UTC, ThePainkiller commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +	desc = "Stalker of nightmare grown in darkness, a rarer mutation has made this verson much more deadly and stronger..."
```suggestion
	desc = "A creature of primal nightmares, bred in pitchest black... a rare sight of an evolved nightmare stalker, much deadlier, ruthless and agile than the average."
```

2021-07-24 05:35 UTC, Kazkin commented
Where is the voxy.dmi sprites? I don't see them.

2021-07-24 05:49 UTC, Trilbyspaceclone commented
was added before, they do infact work ill dm you them

2021-07-24 05:50 UTC, merged