Gauss Rifle, Axe Shotgun, Drum Mags & More
sojourn-13/sojourn-station pull request #3056
Opened 2022-04-09 17:02 UTC by SouthyOsmanli

## About The Pull Request
<details>
<summary>
	This PR is a bit of a mix of things; so I'll break this down by section. A new **gauss rifle** is added to Guild crafting alongside an upgraded Martin energy pistol. The gauss rifle is basically a strong rail rifle, akin to an AMR, but with less chance to gib/blow off limbs and sports less AP than the AMR or bone rifle. It fires refined scrap, has cooling mechanics akin to a hydrogen gun and has slowdown while using it. The upgraded Martin recipe is just a martin with a unique sprite and 25 charge cost instead of 50. The **axe shotgun** is available to anyone. It's a axe on a double barrel - not much more to add other than it's akin to a mosin's bayonet but on a shotgun. **Drum mags** for .257 and 7.5 have been added along with a nerf to .408 drum mag capacity. .257 drums sport 75 rounds, 7.5 sport 50 rounds, .408 sport 36 (apparently 38 was 'too odd' to give it). This is to encourage use of automatics despite their nerfed damage, provide rare high-end mags to allow these lower calibers to compete with .408 and make .408 not an 'end all' with a higher possible capacity over every other gun in the game. **Sprite changes** have happened for all guns effected by drum mag sprites and I've cleaned up the magazine folder a bit; mostly removing duplicate sprites and prettying-up certain magazine sprites like the 7.5 rifle mags. I've also re-organized it to go by caliber rather than just the random 'by implementation'.
</summary>
<hr>
	
<hr>
</details>

## Changelog
:cl:
add: New Guild gauss rifle & its crafting recipe.
add: New Guild 'Overclocked' Martin energy pistol & its crafting recipe.
add: New axe-double barrel shotgun & its crafting recipe; available to all colonist.
add: New drum mags & magazine sprites.
/:cl:

2022-04-09 18:43 UTC, Kazkin commented
This is huge, will review tomorrow.

2022-04-09 18:58 UTC, SouthyOsmanli commented
> This is huge, will review tomorrow.

Over half of the changes are sprites. All simply add a new mag state for the .257 or 7.5 drums since they require one otherwise the entire sprite disappears.

2022-04-09 20:12 UTC, Trilbyspaceclone commented on code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
> +/obj/item/gun/projectile/shotgun/doublebarrel/axe
Give them the baynet flag so you can sharpen it

2022-04-09 22:14 UTC, ThePainkiller commented
Dear god FINALLY ANOTHER USE FOR REFINED SCRAP, I'm all in on this one, pending balance

2022-04-10 13:04 UTC, MSieghardt commented
Looks good.

2022-04-11 01:52 UTC, lolman360 requested changes

2022-04-11 01:52 UTC, lolman360 commented on code/modules/projectiles/guns/energy/railgun.dm
> +	return new projectile_type(src)
```suggestion
/obj/item/gun/energy/laser/railgun/gauss/consume_next_projectile()
        var/datum/component/heat/H = GetComponent(/datum/component/heat)
	if((H.currentHeat > H.heatThresholdSpecial ||stored_matter < projectile_cost || !..())
	    return null
	stored_matter -= projectile_cost
	return ..()
```

2022-04-11 01:52 UTC, lolman360 commented on code/modules/projectiles/guns/energy/railgun.dm
> +	return ..()
```suggestion
```

2022-04-11 01:52 UTC, lolman360 commented on code/modules/projectiles/guns/energy/railgun.dm
> +		..()
```suggestion
/obj/item/gun/energy/laser/railgun/gauss/attackby(obj/item/I, mob/user)
	if(istype(I,/obj/item/gun_upgrade/mechanism/battery_shunt))
		to_chat(user, SPAN_WARNING("[src] cannot be fitted with a battery shunt!"))
		return FALSE
	else if(!istype(I,/obj/item/stack/sheet))
		..()
	var/obj/item/stack/sheet/M = I
	if(istype(M) && M.name == matter_type)
		var/amount = min(M.get_amount(), round(max_stored_matter - stored_matter))
		if(M.use(amount))
			stored_matter += amount
		to_chat(user, "<span class='notice'>You load [amount] [matter_type] into \the [src].</span>")
	else
		return ..()

```

2022-04-11 01:52 UTC, lolman360 commented on code/modules/projectiles/guns/energy/railgun.dm
> +		..()
note: you'll need to fix tabs if you autoincorporate this sugg

2022-04-11 01:52 UTC, lolman360 commented on code/modules/projectiles/guns/energy/railgun.dm
> +	return new projectile_type(src)
note: you'll need to fix tabs if you autoincorporate this sugg

2022-04-11 12:54 UTC, SouthyOsmanli commented
Merged in Lolman's suggested changes - should tidy it up a bit more than how it was before. Thank you for the help!

2022-04-13 07:15 UTC, lolman360 commented on code/modules/projectiles/guns/energy/railgun.dm
> +	return new projectile_type(src)
```suggestion
	return ..()

```
consume_next_projectile() is defined twice and as such will behave oddly (it will ignore heat)

2022-04-13 20:36 UTC, merged