hollowpoint rework, post-penetration damage
sojourn-13/sojourn-station pull request #3321
Opened 2022-05-12 13:25 UTC by lolman360

adds post-pen damage to hollowpoints. nerfs hollowpoint agony by ~66% across the board.

## Changelog
:cl:
balance: hollowpoints deal greater post-penetration damage
/:cl:

2022-05-13 07:15 UTC, ThePainkiller commented
Why add a "post pen" value when hollow points are, by definition, non-pen ammunition meant to deal with unarmored targets...?

2022-05-13 11:22 UTC, lolman360 commented
> Why add a "post pen" value when hollow points are, by definition, non-pen ammunition meant to deal with unarmored targets...?

hollowpoints, by design, are worse at penetrating armor but do more damage when they **do** penetrate. post-penetration damage is a reflection of this, and allows us to have weapons that do more damage against unarmored targets without doing something like a total armor rework with negative penetration

2022-05-13 11:27 UTC, cdb-is-not-good requested changes

2022-05-13 11:49 UTC, cdb-is-not-good approved these changes

2022-05-14 01:14 UTC, cdb-is-not-good commented
Seems to be all working, well test on live and tweak from there the numbers.

2022-05-14 01:14 UTC, merged