Medical Perk-Checking
sojourn-13/sojourn-station pull request #3670
Opened 2022-07-14 23:44 UTC by Stutternov

## About The Pull Request
Adds code to check for Medical's surgery perk (Or herbalist for hunters) to do surgeries or a bio of 120+. Some surgeries are locked behind this - mostly relate to organ repair, bone grafting and other surgery types. Shrapnel removal has seen a **slight** increase in difficulty - but still has a 100% success rate if the person has 40 bio skill basically. Self surgery has also been penalized **heavily** by having a doubled fail-rate from what it was and a doubled time-wait.

As every 'balancing' PR is a take-and-give, I've lowered the requirement to use the advanced kits **heavily**. People who are non-Soteria with a bio skill of 25 (instead of 75) can now use it. This may be adjusted but I felt it's fair since the Absolute ones are 15 bio skill and syringes are also 15 bio skill.

This should make Soteria's job more focused on as it requires people to either use splints to temporarily reduce an injuries' penalty or to go to Soteria. This is mostly a start of my intentions, as I believe allowing players to freely heal themselves of non-major injuries and requiring Soteria or a heavy stat-bypass for more serious injuries. 
	
<hr>
</details>

## Changelog
:cl:
add: Stat/Perk 'locks' for certain surgery types. Only really involves 'complex' surgeries that are not life-saving or simple.
tweak: Edits shrapnel surgery to actually have a tad bit of low-risk 'randomness' to it to encourage people with actual biology skills to do it.
balance: Allows advanced kits to be used again by those of at least 25 bio. (Subject possibly to reduction if needed.) 
/:cl:

2022-07-15 00:27 UTC, cdb-is-not-good commented
Based. Good changes, i assume this is all fully tested?

2022-07-15 01:39 UTC, Stutternov commented
> Based. Good changes, i assume this is all fully tested?

Yes, although I have a change I am making now. Players expressed issue with the high bio check, so, instead I got pitched a few solutions. One I thought was good was one regarding ultra-surgeon giving a bypass perk to allow surgery at the cost of a bit of loss to the biological bonus ultra surgeon gives. That way while someone can do the surgery needed, such as low-pop revival, they risk higher fail rates. 

Basically making it a 'downside' to people in the field and not much of a benefit but good for emergency treatment situations.

2022-07-15 02:47 UTC, Stutternov commented
PR is set now with the changes. Me rn.
https://www.youtube.com/watch?v=PtK_crFV04s

2022-07-15 03:06 UTC, ThePainkiller requested changes
Typo

2022-07-15 03:06 UTC, ThePainkiller commented on code/modules/surgery/surgery.dm
> +			to_chat(user, SPAN_WARNING("You do not have the training necessessary to do this surgery!"))
```suggestion
			to_chat(user, SPAN_WARNING("You do not have the necessary training to do this surgery!"))
```

2022-07-15 03:17 UTC, ThePainkiller commented
Leaving my two cents as medical main even if they'll get ignored:

25 BIO is too easily accessible by anyone, prospies can get that on two level ups very easily. Considering doctors have 40-ish BIO on roundstart, that number ought to be harder to keep these exclusive to actual medical "professionals". I believe 50 BIO is a good middle ground for them. 15 BIO bypass on church kits is laughable, honestly. Why do they even have such low requisites while being the most brute-healing-per-application pack in the game is anyone's guess.

Self surgery penalties were decent enough that even with a hundred BIO I've botched them so far as to jump sensors more than once. Those numbers are a ridiculously high jump to a downright impossible level unless you're a hundred plus BIO. By this point just outright removing self surgery from being a thing does literally the same effect, since you'll have to be four hours into a shift of pure BIO artifact minmaxing leveling to even be able to.

2022-07-15 03:24 UTC, Stutternov commented
> Leaving my two cents as medical main even if they'll get ignored:
> 
> 25 BIO is too easily accessible by anyone, prospies can get that on two level ups very easily. Considering doctors have 40-ish BIO on roundstart, that number ought to be harder to keep these exclusive to actual medical "professionals". I believe 50 BIO is a good middle ground for them. 15 BIO bypass on church kits is laughable, honestly. Why do they even have such low requisites while being the most brute-healing-per-application pack in the game is anyone's guess.
> 
> Self surgery penalties were decent enough that even with a hundred BIO I've botched them so far as to jump sensors more than once. Those numbers are a ridiculously high jump to a downright impossible level unless you're a hundred plus BIO. By this point just outright removing self surgery from being a thing does literally the same effect, since you'll have to be four hours into a shift of pure BIO artifact minmaxing leveling to even be able to.

If staff prefer I'd be 100% in favor of removing self surgery as it is, the only reason I didn't is due to FBPs and tool upgrade ability to negate downsides of self-surgery. 

I've only seen it used by players doing surgery on themselves in the field and using certain species who do not feel pain or hyping up on painkillers for it.

2022-07-15 21:34 UTC, Stutternov commented
> I feel like 25 bio for ATKs is honestly fine, particularly given that while it will allow even a relative amateur to clear serious burns/brute they still won't be able to fix organs, bones, brains, etc. At least, if i understand this right.

Correct. You'd be limited by the surgery's bio-requirement of 50 minimum or the bypass perks. To use the ATK kit in surgery it requires 50 bio default. Funnily I didn't even need to change that, it was already like that.

2022-07-15 22:55 UTC, Stutternov commented
Added a small update fixing a possible error/oversight (?) I saw in other code lines of splints supposed to make stuff unable to do surgery past. Not a big change, really mild, but I guess it fixes that since I got it working.

Simply makes splinted limbs require the splint to be removed to operate on the limb. So, same as usual, just remove the splint to do surgery on it.

2022-07-17 11:52 UTC, cdb-is-not-good commented
Unless someone offers a complaint against this PR i'll likely merge this tomorrow

2022-07-18 08:45 UTC, merged