Mostly fixes to the new lodge map.
sojourn-13/sojourn-station pull request #3950
Opened 2022-09-11 12:14 UTC by Guidesu

## About The Pull Request

![image](https://user-images.githubusercontent.com/67030229/189526875-386f8bba-c723-4d5a-ad54-974b18fac0d9.png)
![image](https://user-images.githubusercontent.com/67030229/189526896-3a271b9c-209e-4adb-98d7-ee615dfe187e.png)
![image](https://user-images.githubusercontent.com/67030229/189526907-56cd637f-47f6-41ed-943d-7e21f86c37d3.png)
![image](https://user-images.githubusercontent.com/67030229/189526921-5bb3adf9-301f-44b4-acdb-842ac984005e.png)

</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

2022-09-11 12:19 UTC, Guidesu commented
I added a few doors to places that needed it.
I added an extra door to the master office and I put another fax machine so hunters might use it on one of the shacks.
I fixed the lockers issue and the sharpening block and removed some of the starting materials aswell.
Removed the organ fab and gave some extra organs instead.
Replaced the gate with R-wall due to the nature of the location of being the first defense of the place.
Added a alchemy set at one of the shacks due to what me and Trilby intended to give hunters an archaic method of making chems.



![image](https://user-images.githubusercontent.com/67030229/189527110-8a5f9b21-5673-4766-b74f-4a68f2ee820b.png)
![image](https://user-images.githubusercontent.com/67030229/189527116-f8cd2d0c-06d5-429b-bcb0-996a750f21dd.png)

2022-09-11 12:21 UTC, cdb-is-not-good commented
Something actually does occur to me- didn't they have a proper surgery table on the last map?

2022-09-11 12:22 UTC, Guidesu commented
![image](https://user-images.githubusercontent.com/67030229/189527212-42f002b0-d413-4ceb-80f5-1a09adfb6d0d.png)


> Something actually does occur to me- didn't they have a proper surgery table on the last map?

They had.

2022-09-11 12:24 UTC, Guidesu commented
New:
![image](https://user-images.githubusercontent.com/67030229/189527355-2b04fc5d-063c-4d21-b45c-bcab15323590.png)
Old:
![image](https://user-images.githubusercontent.com/67030229/189527372-9a0ca054-38b3-4751-b6b5-8ad8cd6323b3.png)

2022-09-11 12:24 UTC, cdb-is-not-good commented
also for the record I meant a guncase like ah- 
![image](https://user-images.githubusercontent.com/87905328/189527358-fa761f19-67ac-4814-b347-75ed223c051d.png)

This. im p retty sure it can hold other guns as well

2022-09-11 12:29 UTC, Guidesu commented
> also for the record I meant a guncase like ah- ![image](https://user-images.githubusercontent.com/87905328/189527358-fa761f19-67ac-4814-b347-75ed223c051d.png)
> 
> This. im p retty sure it can hold other guns as well

I think giving them a gun that was intended to HM get would be alright

2022-09-11 18:22 UTC, Trilbyspaceclone commented
gate should be wood
star-striker should be back on the wall like it was
water in the river is also an annoying thing

2022-09-11 18:23 UTC, Trilbyspaceclone requested changes
the above commit

2022-09-11 18:26 UTC, Trilbyspaceclone commented
I also dislike the xenobotney stuff

2022-09-11 19:39 UTC, Guidesu commented
> I also dislike the xenobotney stuff

All done

2022-09-11 19:39 UTC, Guidesu commented
Water is good the overlay is nice.

2022-09-11 19:59 UTC, Trilbyspaceclone commented
theirs a locker of some kind on the herblist spawn in the medical bay area

2022-09-11 20:00 UTC, Guidesu commented
> theirs a locker of some kind on the herblist spawn in the medical bay area

OPS did not sat that ksksksk thank you

2022-09-11 21:53 UTC, cdb-is-not-good commented
> gate should be wood star-striker should be back on the wall like it was water in the river is also an annoying thing

Why?

2022-09-11 23:36 UTC, Trilbyspaceclone commented
metal gate dosnt look good
Star striker dosnt have ammo you shouldnt even be taking it down, if you ruin it for the round to bad
water decals are performance heavy and dont look good/cover up and darken water

2022-09-12 00:10 UTC, cdb-is-not-good commented
> metal gate dosnt look good Star striker dosnt have ammo you shouldnt even be taking it down, if you ruin it for the round to bad water decals are performance heavy and dont look good/cover up and darken water

If it's just there for display than surely it should just be in a display case :p

2022-09-12 03:25 UTC, cdb-is-not-good commented
Also something that someone pointed out and I kind of agree- use the regular dirt/grass tiles rather than the..... Underbrush looking stuff

2022-09-12 07:03 UTC, Memedoktor commented
personal request but could we get an agri fridge again so storing foodstuffs is manageable with all the various produce and eggs and the like

2022-09-12 11:04 UTC, Guidesu commented
> personal request but could we get an agri fridge again so storing foodstuffs is manageable with all the various produce and eggs and the like

When I arrive home I will continue

2022-09-12 22:25 UTC, Trilbyspaceclone approved these changes

2022-09-12 23:09 UTC, TheSleepyCatmom commented
Asking @cdb-is-not-good to actually review this in game to make sure it's not fucky-wucky.

Also make sure to halve the spawn amount of the scrap area, replace the 'paths' with actual dirt like we do in the colony and elsewhere, and replace the 'grass' with the grass tiles we use everywhere else too.

2022-09-13 00:32 UTC, cdb-is-not-good commented
> Asking @cdb-is-not-good to actually review this in game to make sure it's not fucky-wucky.
> 
> Also make sure to halve the spawn amount of the scrap area, replace the 'paths' with actual dirt like we do in the colony and elsewhere, and replace the 'grass' with the grass tiles we use everywhere else too.

Will do a walkthrough once the requested changes are made.

2022-09-13 22:39 UTC, Guidesu commented
Alright i will s tart to work it in a moment...
i LOST everything due to energy shortage

2022-09-13 22:40 UTC, Guidesu commented
I so tired from the college ;-;

2022-09-14 06:13 UTC, Memedoktor commented
Btw i think theres something wrong the implantable bolt lance in the Hunt master armory. i think they're acting like regular bolt lances instead of the implantable kind.

2022-09-15 03:42 UTC, Trilbyspaceclone commented on maps/_HunterLodge/map/_Hunting_Lodge.dmm
> +	name = s"\improper Refrigerated Seeds Storage"
```suggestion
	name = "\improper Refrigerated Seeds Storage"
```

2022-09-15 03:52 UTC, Guidesu commented
going sleep
please leave a review <3

2022-09-15 03:56 UTC, Guidesu commented
> I did a bit of a goof and used the old map for reference, kekw.
> 
> To reiterate my points that are still relevant
> 
> -Lodge goofy ahh -Many places have been outright downgraded from previous iterations (see below)
> 
> ![image](https://user-images.githubusercontent.com/65188584/190309644-73136a2a-b089-45e5-b6f6-818ccb122d74.png) -Barns and botany now require you to walk halfway across the lodge, then halfway back again (Bad design) ![image](https://user-images.githubusercontent.com/65188584/190309694-85c9c3a8-2e30-4e92-961c-feb67073b562.png) -Botany is goofy again because now they get access to arguably the most OP machines that allow them to make any chemical in the game, the electrolyser, as it allows them to turn any medicine or chemical into its prerequisite components. Which essentially means: Everything
> 
> ![image](https://user-images.githubusercontent.com/65188584/190309763-26f662a4-8d8f-4eb8-b0ef-1f825a47b431.png) -Bar is incredibly goofy, doesn't even have enough seats for the full lodge slots.
> 
> ![image](https://user-images.githubusercontent.com/65188584/190309816-082d3bd1-bc65-4809-b0a8-56d7f0284b18.png) -No surgical table? But you give them organs? A?
> 
> Also lodgers have like a 1% chance to succeed in organ replacement since Kazkins old medical PR, even with 80+ bio, trust me.
> 
> ![image](https://user-images.githubusercontent.com/65188584/190309867-e730b320-e9d3-4e4a-8b73-ffe688e42a59.png) -Every outsider in 10,000KM is now rushing the lodge roundstart
> 
> ![image](https://user-images.githubusercontent.com/65188584/190309891-dabf415a-67f7-4ee5-b312-9f99403091aa.png) -Goofy and will cause later balance concerns (e.g lodge no longer having to trade for mats). Also encourages the lodge to go and mine for plasteel/etc as they can make more weapons from that.
> 
> ![image](https://user-images.githubusercontent.com/65188584/190309979-18802fde-a9d6-4cdf-b696-8b3173052c41.png) -Why is the huntmasters office bigger than most of the small 'departments' the lodge has? Why is it bigger than the actual medical bay?
> 
> ![image](https://user-images.githubusercontent.com/65188584/190310051-cff6b0f3-211a-45a8-95ff-604252854079.png) -Goofy goober gatehouse, you implement the metal walls but forget to make the doors have blast-doors round-start that start closed to prevent instant looting via doorhacking, or by just breaking the door

Aren't you perma banned from Sojourn?

2022-09-15 03:58 UTC, Guidesu commented
And you are still using the older version so.
Dully iguinored

2022-09-15 04:04 UTC, Guidesu commented
> > > 
> > 
> > 
> > Aren't you perma banned from Sojourn?
> 
> Yeah and? You still have downstream this PR will trickle to.
> 
> Afterall, Risikio was also banned but was allowed to contribute game-changing PRs with literally zero testing that had to undergo changes almost immediately.

sniff.
I don't care about risiko.
I will not take criticism from someone who does not play or has access to the server anymore.
Have a good night.

Even if you have your points I am not in the mood its 01:02 and to be fairly honest I don't want to shape or change the map to someone with a power gaming point of view that plus that are not even on the server anymore.

I am taking feedback from the community you are not in the community

2022-09-15 04:08 UTC, Guidesu commented
Take with a grain of salt.
Feedbacks are okay. You had your points but I don't and nor will bend over to make changes unless that Trilby/CDB or anyone who wants wishes to change. Community opinions are always welcome though don't feel necessary to take feedback from a person again that is permabanned.

Now I going to sleep

2022-09-15 18:36 UTC, cdb-is-not-good commented
Kay, review time. 

First off, the grass wasn't entirely fixed. Still looks notably better, but in areas like this it's just - not good. Contrast is important, and having entirely samey tilesets all side by side it looks meh.
![image](https://user-images.githubusercontent.com/87905328/190481249-d6f4d4fb-9df6-4640-9be4-4b5599d58981.png)
![image](https://user-images.githubusercontent.com/87905328/190482711-42f348e8-9d2b-4383-afee-3f06de3dc76a.png)


Machine spawns aren't fixed either. If you're using random spawns with a chance to be zero, use less. 
![image](https://user-images.githubusercontent.com/87905328/190481334-944cbc0f-0019-4c86-a128-c4f5f2b65c16.png)

Small issue with medical- that morgue tray is unusable. You can't stand in front of a tray and open it, and it opens onto the only tile from which you can access it. Other than that, looks fine.
![image](https://user-images.githubusercontent.com/87905328/190481597-992379e8-ad8d-48b1-8f10-2876513d6e5d.png)

farming area- gonna be real, it's a bit of a mess. Having all the mounds just in a pile along the wall both looks bad and means constantly stepping over them, which while...lacking gameplay effect, is still just...looks sloppy. dont do this.
![image](https://user-images.githubusercontent.com/87905328/190481732-dd4dcc13-6a9a-4d8b-8931-6022bf92f245.png)

![image](https://user-images.githubusercontent.com/87905328/190482072-07676ac4-599f-45f1-9df9-a3c6465c2b65.png)
Gate- generally looks fine. why do they have a hoverpod, though? Or a cyborg auto-repair station? Why? a recharger i can accept especially with all the talk of making synths have to recharge, but the rest seems...superfluous? also some of the walls are still steel(the window walls particularly), i do think we have wood low walls. 

![image](https://user-images.githubusercontent.com/87905328/190482573-bf6de058-e135-4be2-8cfd-9790219a2500.png)
why? Why did you put this here? The lodge doesnt need access to drone/circuit stuff.

![image](https://user-images.githubusercontent.com/87905328/190482912-731421cf-f1f9-49da-a461-9d0ef9cd7c73.png)
Why?

![image](https://user-images.githubusercontent.com/87905328/190483006-4555060c-2705-4622-a271-7b3aa9eb3b07.png)

Actually i stand corrected about med. 5 o negative? really? also 8 toolboxes in the storage area is a big "???"

Final conclusion; still needs work.

2022-09-15 18:42 UTC, TheSleepyCatmom requested changes
Removal of the xenobotany explicit equipment and requirement to change things as requested by @cdb-is-not-good . Fix the flooring to be uniform for grass.

2022-09-22 15:21 UTC, Trilbyspaceclone submitted a review, later dismissed
remove the CBO's runtimes cardboard box
the stair spam looks not that good
please make the paths grass again
please remove the water decals form the water

2022-09-22 16:39 UTC, cdb-is-not-good commented
new review let's go.

![image](https://user-images.githubusercontent.com/87905328/191802450-34b33d7f-f6ad-44e6-a127-999e91099de4.png)
Why have that gap in the wall?

![image](https://user-images.githubusercontent.com/87905328/191802550-bfa04b72-c974-41a1-8cf3-7fd3afbd2320.png)
![image](https://user-images.githubusercontent.com/87905328/191802688-28189156-d8ec-4de5-9702-f7b0f6a118a7.png)
I think I already complained about having massive amounts of blood. 6 bags of O- might be way too many. Ditto on three whole tubes of nanopaste.

![image](https://user-images.githubusercontent.com/87905328/191802951-f34689a4-d503-4195-be1e-a89aa0d4120b.png)
I'm assuming there's just a buncha 'loot' spawns on this one rack, but why?

![image](https://user-images.githubusercontent.com/87905328/191803261-296c9cdb-828e-439a-b5eb-080e7570fcf2.png)
???? why stack so many of these on top? why not use regular reinforced windows? I guess it works but you should probably move it to be just one barricade+one grill and maybe a full window over top. It's a little janky to stack them like this.

![image](https://user-images.githubusercontent.com/87905328/191803670-9b2afc13-29c8-464a-9fd9-8b1aff2867df.png)
That's a lotta medkits.

![image](https://user-images.githubusercontent.com/87905328/191803814-a3ea198a-69ab-4198-a021-b2920b99292d.png)
Why is this even here? 

Still a few things that could use adjustment I M O but substantially better than before.

2022-09-23 11:07 UTC, Trilbyspaceclone commented
Still needs liches approval as well

2022-09-27 17:37 UTC, TheSleepyCatmom commented
I'll consider these issues minor. I don't know what Lich's github is but someone poke him for this.

2022-09-28 15:00 UTC, Medizeal22 commented
Okay. Loaded it up and took a few pictures of things that need to be considered. Firstly, thank you for putting this together as well as you have. I do have some overarching and some specific concerns I'll list out here.

1. 
![image](https://user-images.githubusercontent.com/46577686/192810374-c128baa4-f232-41da-90b4-75a71ac2c30a.png)
![image](https://user-images.githubusercontent.com/46577686/192810996-4d9f149b-20b3-4255-9cbc-c0e5b66defaa.png)
Double beds in the rooms beyond the little isolating room. Also take note of the the stairs that lead into the room. The direction may be off but it doesn't look "right" with how the room is structured. Consider using a door instead for these parts or just a curtain. If there was 1 tile either east or west then it'd be more simple to simply put the stairs then the curtains, sequentially rather than on top of one another.

2. 
![image](https://user-images.githubusercontent.com/46577686/192811034-2ae01607-5a3f-4feb-945b-86ad7db79268.png)
This solar panel APC room confuses me. It's either too big or that random solar in there just needs to be elsewhere. It doesn't make a lot of sense.

3. 
![image](https://user-images.githubusercontent.com/46577686/192811323-e8fe9cc0-9c70-475c-952b-e4254ee60ec6.png)
Consider using a different material / set up for this as the textures are clipping here, causing only 3/4ths of the window to actually take up the space expected.

4. 
![image](https://user-images.githubusercontent.com/46577686/192811457-03009a7f-44ee-4848-9a80-72dc634a894d.png)
For some reason this smashes out round-start. Please check same.

5.
![image](https://user-images.githubusercontent.com/46577686/192811574-f1fdeac2-7bde-436d-9634-6768c794aa3a.png)

Is this necessary? See rant below for rational.

6.
![image](https://user-images.githubusercontent.com/46577686/192811661-8f593314-19c1-4a00-8667-5bea273445df.png)

Flooring in this room is jarring and confusing. Please make it more uniform and friendly to look at.



--------------------------------------------

So I love the new look of the Hunter's Lodge, especially if it actually does bring people back to the Lodge. There are some BIG WARNINGS I would like to push out though about the overall "strategy" that a number of mappers have been pushing for with it that has been a hot-topic of mine for years.

When you're trying to influence players to come back to an area, bigger is NOT better. In fact, bigger kills off your population's interest twice as fast. The reason why is because something this big and spread out encourages people to isolate themselves from one another. Considering there will be around 5 hunters on the better side of average, this means that they're less likely to see one another and contributes to a feeling of the compound (which is what this is now, it's not really a lodge anymore) feeling dead. My recommendation is to cut back on the number of "isolation" rooms as a result. I am NOT saying to get rid of all of them, I am saying to consider reducing the number of them as to encourage players to see one another more often. Remember, the philosophy of the lodge is that they are NOT Nadezhda nor are they trying to REPLACE Nadezhda. They're a group of people who more or less choose to live a more naturalistic lifestyle and their resources and technology should reflect that. They're NOT super advanced nor are they to expected to be competitively equipped as Nadezhda. Resist the urge of making the lodge the "do anything without security" space.

Another thing I am noticing is that there are a number of "doors with curtains". This is an effective strategy if used in small numbers. It's used excessively here to the point it becomes a bit of an unnecessary annoyance. I recommend  you use one or the other, but not always both. This goes with stairs as well. Make sure the direction and use of them makes practical sense. They don't need to be in the threshold of every room as it does raise some questions about relative elevation that need not be brought up really.

I'm curious to see what the water textures will do to the server. I would caution against them to some degree and heed any warning that Trilby gives you about using them. On solo-play it seems fine but when you put it on the live server it may contribute to lag.

Finally, consider naming your doors. This will help people figure out where things are a bit more easily without having to add a bunch of unnecessary windows.

2022-10-07 14:14 UTC, Guidesu commented
kavrick is working on the new lodge.
Which he is a way better mapper than me.

2022-10-07 14:14 UTC, closed without merging