Ichor redone.
sojourn-13/sojourn-station pull request #451
Opened 2020-10-02 02:43 UTC by Abatha

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

2020-10-02 08:56 UTC, KathyRyals requested changes

2020-10-02 08:56 UTC, KathyRyals commented on code/game/objects/items/stacks/medical.dm
> +	origin_tech = list(TECH_BIO = 2)
Already defined in parent type, no need to add it here.

2020-10-02 08:56 UTC, KathyRyals commented on code/game/objects/items/stacks/medical.dm
> +	preloaded_reagents = list("silicon" = 4, "ethanol" = 10, "mercury" = 4)
Same.

2020-10-02 08:56 UTC, KathyRyals commented on code/game/objects/items/stacks/medical.dm
> +	origin_tech = list(TECH_BIO = 2)
Already defined in parent type. That means your mending_ichor type will already inherits these values from the bruise_pack parent, so you don't have to define them.

2020-10-02 08:56 UTC, KathyRyals commented on code/game/objects/items/stacks/medical.dm
> +	preloaded_reagents = list("silicon" = 4, "ethanol" = 10, "lithium" = 4)
Same.

2020-10-02 09:39 UTC, KathyRyals approved these changes

2020-10-03 15:39 UTC, Kazkin commented
This is much cleaner and significantly improved compared to the first draft, while frustrating, this code is as clean as my own. Approved.

2020-10-03 15:39 UTC, merged