silk
sojourn-13/sojourn-station pull request #481
Opened 2020-10-10 08:59 UTC by Trilbyspaceclone

## About The Pull Request
Spider webs got a buff of sorts, you can now harvest silk into the new ~~wood based ecom but more balanced~~ cash trade item that can even be given/sold to the faith as it has when broken down, biomatter. - Irl silk is a massive proteen so this is infact based in logic
To get this you must have the proper tool - A silk harvester wand
A death wish
And a spider farm or nest
## Changelog
:cl:
/:cl:

2020-10-10 16:05 UTC, MSieghardt commented
Balance issue:
Spider Cht'Mants can weave webs themselves, making them a farm of infinite good money. They are also friendly to spider, making it a no-hassle abuse-able money farm.

2020-10-11 12:11 UTC, KathyRyals requested changes

2020-10-11 16:19 UTC, Trilbyspaceclone commented on code/modules/materials/materials.dm
> +	composite_material = list(MATERIAL_BIOMATTER = 1) //So we have a vaule to more then one faction
to the church

2020-10-11 16:20 UTC, Trilbyspaceclone commented
@MSieghardt 
Spider farms are intended

2020-10-11 17:04 UTC, KathyRyals commented
Won't merge until you find a way to prevent PC farming silk by spamming their web perk.

2020-10-11 20:49 UTC, Kazkin commented
Aye, my suggestion is make a subtype of web that has value 0, biomatter 0, and a different name/description that the player perk generates instead of the standard webs. That way we don't have system gaming.

2020-10-11 22:07 UTC, Trilbyspaceclone commented
give me a day or two then.

2020-10-12 20:28 UTC, KathyRyals commented
Looks good.

2020-10-12 20:28 UTC, merged