Bioprinter changes
sojourn-13/sojourn-station pull request #5040
Opened 2024-02-13 20:06 UTC by Trilbyspaceclone

Inconstantly upto half reduced all church prints 
changes biomatters 50% reduction in printing to a reduction of 25%

2024-02-14 21:01 UTC, SingingSpock requested changes

2024-02-14 21:01 UTC, SingingSpock commented on code/modules/core_implant/cruciform/rituals/construction.dm
>  	name = "Absolutism Medkit"
Could you actually comment out this recipe? It's a good idea, but I haven't figured out how to stop our resident powergamers from printing it with the printer and then Uprooting it to get free mats

2024-02-14 21:07 UTC, Trilbyspaceclone commented on code/modules/clothing/suits/armor.dm
> +	matter = list(MATERIAL_PLASTEEL = 30, MATERIAL_PLASTIC = 5, MATERIAL_SILVER = 5, MATERIAL_GOLD = 5)
its the same amount of plasteel as its always been to print for the church biolathen

2024-02-14 21:14 UTC, Trilbyspaceclone commented on code/datums/autolathe/biomatter.dm
> +	materials = list(MATERIAL_BIOMATTER = 70, MATERIAL_GOLD = 5, MATERIAL_SILVER = 5, MATERIAL_PLASTEEL = 50)
its 50% + 25%
your accually getting a better deal on this print then before

2024-02-14 21:21 UTC, SingingSpock commented on code/datums/autolathe/biomatter.dm
> +	materials = list(MATERIAL_BIOMATTER = 70, MATERIAL_GOLD = 5, MATERIAL_SILVER = 5, MATERIAL_PLASTEEL = 50)
Yes, that's the issue. New price is too low imo.

2024-02-14 21:23 UTC, SingingSpock commented on code/modules/clothing/suits/armor.dm
> +	matter = list(MATERIAL_PLASTEEL = 30, MATERIAL_PLASTIC = 5, MATERIAL_SILVER = 5, MATERIAL_GOLD = 5)
Previous cost with a bioprinter: 50% of 60 plasteel: 30 plasteel. New cost with a bioprinter: 75% of 30 plasteel: 22.5 plasteel. I recommend a new price of 40, as that will keep the cost with bioprinter unchanged

2024-02-15 01:23 UTC, Trilbyspaceclone commented on code/modules/clothing/suits/armor.dm
> +	matter = list(MATERIAL_PLASTEEL = 30, MATERIAL_PLASTIC = 5, MATERIAL_SILVER = 5, MATERIAL_GOLD = 5)
```suggestion
	matter = list(MATERIAL_PLASTEEL = 40, MATERIAL_PLASTIC = 5, MATERIAL_SILVER = 5, MATERIAL_GOLD = 5)
```

2024-02-15 01:23 UTC, Trilbyspaceclone commented on code/modules/clothing/suits/armor.dm
> +	matter = list(MATERIAL_PLASTEEL = 30, MATERIAL_PLASTIC = 5, MATERIAL_SILVER = 5, MATERIAL_GOLD = 5)
```suggestion
	matter = list(MATERIAL_PLASTEEL = 40, MATERIAL_PLASTIC = 5, MATERIAL_SILVER = 5, MATERIAL_GOLD = 5)
```

2024-02-15 01:23 UTC, Trilbyspaceclone commented on code/modules/projectiles/guns/energy/laser/laser.dm
> +	matter = list(MATERIAL_PLASTEEL = 15, MATERIAL_WOOD = 8, MATERIAL_SILVER = 1)
```suggestion
	matter = list(MATERIAL_PLASTEEL = 15, MATERIAL_WOOD = 8, MATERIAL_SILVER = 6)
```

2024-02-15 01:24 UTC, Trilbyspaceclone commented on code/datums/autolathe/biomatter.dm
> +	materials = list(MATERIAL_BIOMATTER = 70, MATERIAL_GOLD = 5, MATERIAL_SILVER = 5, MATERIAL_PLASTEEL = 50)
```suggestion
	materials = list(MATERIAL_BIOMATTER = 70, MATERIAL_GOLD = 7, MATERIAL_SILVER = 7, MATERIAL_PLASTEEL = 70)
```

2024-02-26 00:07 UTC, merged