Pouch "rebalance"
sojourn-13/sojourn-station pull request #5384
Opened 2024-05-30 21:45 UTC by Trilbyspaceclone

Hey hey catto here from back from hell and me and the fallen have been chitchatting before seeking otherworldly advice for tweaking the balance of storage!

Pouches are now "soft storage" for sake of mechanical refence, what that means is that more items put in the more it grows in size well in modular storage.
Pouches default size has been lowered by 1 weight class.
Putting items of the higher weight class into the soft storage increases its size by the difference 
An exsample
Small pouch is tiny! code wise thats a weight class of 1
You put a medium cell in, thats small and thats a class of 2
so the pouch grows for having an item inside it and then an additional 1 extra bulk for the cell.
This system does NOT prevent you from having big sized pouches in pockets or slotted storage.

2024-05-30 21:58 UTC, Legate-Maxson commented
I think it's neat

2024-05-30 22:00 UTC, SingingSpock requested changes
These will naturally need to be updated where they're used too

2024-05-31 01:52 UTC, benj8560 commented
![dreamseeker_5OFKaAmuKT](https://github.com/sojourn-13/sojourn-station/assets/26511091/d7dcedd0-7d16-44cc-8079-0b8de32eecc4)

pouches can go on ears funny.

2024-06-01 17:26 UTC, Trilbyspaceclone commented
![image](https://github.com/sojourn-13/sojourn-station/assets/30435998/475ec7cf-291b-4648-bb5b-b245064f9d32)

2024-06-02 16:33 UTC, Trilbyspaceclone commented on code/game/objects/items/weapons/storage/pouches.dm
> +	plus_extra_bulk = 2 //Anti-quatom scaling with smaller items
```suggestion
	plus_extra_bulk = 1 //Anti-quatom scaling with smaller items
```

2024-06-04 14:50 UTC, merged