Xenobio batong
sojourn-13/sojourn-station pull request #5900
Opened 2024-12-07 13:49 UTC by Lamasmaster

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Makes xenobio baton do same agony as mini baton, it's meant against slimes (where you can use water already) not humans, so why does it do almost same damage as a maul.
	
<hr>
</details>

## Changelog
:cl:
balance: Xenobio stun baton
fix: Typo in xenobio stun baton description
/:cl:

2024-12-07 16:58 UTC, du-top commented
Salt PR because addi loves that baton very verbally?

2024-12-07 20:01 UTC, Lamasmaster commented
No because some things are long overdue.

2024-12-09 08:03 UTC, Smokingsquirrel commented
So the old one had 50 agony and the security stun baton along with the improvised one has 40 agony. The Gloves have 30. 
I agree on 50 being way too much but 20 is probably not enough. 

I would suggest putting 25.

2024-12-11 03:06 UTC, Trilbyspaceclone requested changes

2024-12-11 03:06 UTC, Trilbyspaceclone commented on code/game/objects/items/weapons/tools/stunbatons.dm
> +	agonyforce = 20 //No
```suggestion
	agonyforce = 30
```
Its expensive, and you can do the same meme setups to 1 tap everyone (and better) with normal baton you can print with a sec disk/genetics free baton

The issue is that tool upgrades for hit cost directly also mult agonyforce as seen [here](https://github.com/sojourn-13/sojourn-station/blob/master/code/game/objects/items/weapons/tools/mods/_upgrades.dm#L371).

2024-12-11 06:43 UTC, ChefDoggo commented
![image](https://github.com/user-attachments/assets/71c1c042-5188-4a72-99aa-0917000dee01)

2024-12-11 06:45 UTC, AMcilraith commented
I'm going to cite both the contributor guidelines, and say: You cannot nerf it more than 25. That's over the 50% nerf we permit.

Secondly, it is extremely expensive to get it to the quantity we do. At least 100k research points go into getting the greyson parts unlocked, platinum, gold, silver.

It's very much a late-round gain. 50 is also not too much when you consider how slimes are handled. The one-tap baton is HEAVILY upgraded with HIGHLY EXPENSIVE parts. It's not simple.

Also, for the record, it does NOT one tap people. One tapping implies it takes one hit and it's done. It stuns them, and at around minimum robustness, even with one hit, it takes upwards of 30-40 seconds for the person to go down.

Compare that with a more robust person, i've seen some take 3-4 hits before that thirty second mark even becomes an issue.

This is clearly a salt-PR. I'm advising it be denied.

2024-12-11 06:49 UTC, AMcilraith commented
Also dropping it from 50 to 25/30 will prevent it from killing slimes in one hit.

That needs to be fixed in some way.,

2024-12-11 08:00 UTC, Smokingsquirrel commented
Okay given the explanation and costs included, 20 does seem a bit low lmao.

2024-12-11 14:30 UTC, Trilbyspaceclone reviewed
I still need to think this over more.
Its major use is 1 tapping slimes, with a newer side use of anti-hostile mobs in genetics I guess?
Like its more expensive, cost more per hit and if its less good then a normal baton then why get it (outside of xenoarch).

2024-12-12 20:09 UTC, Trilbyspaceclone commented
After a long thing and such. I do not think this is a good change.
It does not properly fix the issue of batons being some of the best scaling weapons in the game.

A better fix would be to change how much agony force force is scaled up by power cost as stated in previous reviews.

The spelling fix is approved tho.

2024-12-12 20:11 UTC, merged