Update hammer.dm
sojourn-13/sojourn-station pull request #997
Opened 2021-03-24 11:36 UTC by Chevalt

Description : 
A simple change to the charge hammer, making it suitable for the belt slot, considering the foreman's hammer and homewrecker could already do that.

## Changelog
tweak: tweaked a few things
fix: fixed a few things

2021-03-25 01:06 UTC, ThePainkiller requested changes
This should make it compile.

2021-03-25 01:06 UTC, ThePainkiller commented on code/game/objects/items/weapons/tools/hammer.dm
> +	slot_flags = SLOT_BELT|SLOT_BACK
```suggestion
	slot_flags = SLOT_BELT | SLOT_BACK
```

2021-03-25 01:07 UTC, ThePainkiller commented on code/game/objects/items/weapons/tools/hammer.dm
> +	slot_flags = SLOT_BELT|SLOT_BACK
Oh wait, it works just as fine, nvm feel free to ignore

2021-03-25 12:19 UTC, king5327 commented
I'd personally say nah because the rocket hammer has the whole 'charge' feature too, but I don't really use it so I can't say.

2021-03-27 00:34 UTC, Kazkin commented
I'd say its fitting for it, personally, the rocket hammer is a junk weapon and it makes semi-sense it can't fit the belt. If someone makes a Pr I don't mind giving all 2h sledges belt slot AND suit slot.

2021-03-27 00:34 UTC, merged